### ISSUE TITLE
Integer overflow in compress_state

### ISSUE THREAD

**Issue by rmccampbell** [polylog-cs/rubiks-cube-video#1]
Hi, I noticed your compress_state function has a potential integer overflow (whenever either half of the state starts with E or F I think). This is because you're doing the multiplication after the addition. If you swap the order then the overflow should be solved:
```
  for (int i = 0; i < 24; ++i) {
    fst *= 6;
    fst += state[i] - 'A';
  }
```
I'm not sure if this actually effects the results, since it's unsigned the overflow will wrap around deterministically but it could cause collisions between states.

**Comment by vaclavrozhon** [comment]
Thanks! Good catch, I will change it. :)
